### ISSUE TITLE
Implementing index_select over multiple dimensions

### ISSUE THREAD

**Issue by bcsaldias** [harvardnlp/namedtensor#28]
I was thinking that index_select over multiple dimensions may be implemented in at least two ways:

index_select(input:namedtensor, dims:tuple, indices:namedtensor)
dims: dimensions to index using indices

a) indexing and then concatenating (I have this. I'm not sure we can backdrop through it though.)
b) implementing __getitem__ and __setitem__ (pytorch vs numpy magic indexing)

Any thoughts on this? Thanks

**Comment by srush** [comment]
Good question. So we definitely can't back prop through this, but it is still really useful.

Let's do it with index_select first, roughly as you said. I think you need to give two dim args. One for the list of n-input tensor dims to be indexed, and the other for the name of the dimension of size n in the index tensor. It should result in a new tensor with K - n + 1 dims. where the +1 has the name of the other dim in index.

**Comment by bcsaldias** [comment]
Ouch! I accidentally sent two different functions on the same PR.

I have a proposal that I'd love you can give feedback on it. So it's called ```multi_index_select(tensor, dims, indices)```. 

Basically, dims refers to the name of dimensions to be indexed by indices; dims must be names of tensor dimensions (no particular order required).
