### ISSUE TITLE
Implementing a `masked_fill_` function and [] square bracket masking

### ISSUE THREAD

**Issue by samgoldman97** [harvardnlp/namedtensor#44]
In torch,  you often want to change the values of a tensor at specific index. For instance, when converting from bag of words representation to set of words representation, you may want to index into the tensor and modify all indices that indicate a bag of words and change them to a set:
`tensor[tensor > 0] = 1`
In namedtensor, this becomes difficult. Even without this indexing notation, a similar function, such as `masked_set` could make this easier

**Comment by srush** [comment]
The functions we need for this are:

masked_fill_(mask, value)
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.masked_fill_

masked_scatter_(mask, source)
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.masked_scatter_

We could potentially implement index notation for this.

**Comment by srush** [comment]
btw, both would be straightforward to add. Just copy this function. 

https://github.com/harvardnlp/namedtensor/blob/master/namedtensor/torch_base.py#L93

If you want the square brackets [] (which I think is fine for masking), then override

https://docs.python.org/3/reference/datamodel.html#object.__setitem__

**Comment by srush** [comment]
Think this is fixed now https://github.com/harvardnlp/namedtensor/blob/master/README.md#named-indexing
