### ISSUE TITLE
Colab Link in the article is broken.

### ISSUE THREAD

**Issue by ghost** [harvardnlp/namedtensor#5]
![screenshot 85](https://user-images.githubusercontent.com/43285614/50747272-0e21db80-1259-11e9-8c26-92060658d7f3.png)
Link is broken as the NamedTensor notebook is now in notebooks folder of the master branch.
Should I make a few colab notebook and submit a pull request?

Loved the work and the insanely well written article. To NamedTensors 🥂

**Comment by srush** [comment]
Thanks for the heads up, fixing now.

**Comment by srush** [comment]
Blog is updated, should link should be fixed too.
