### ISSUE TITLE
Not Contributor friendly I guess

### ISSUE THREAD

**Issue by ghost** [harvardnlp/namedtensor#9]
As someone who loved the idea of NamedTensors and as someone who is keen to make sure that namedtensor gets into the Pytorch ecosystem ( as a contributor obviously) , the documentation is a little depressing. And can be done about this , so that it's a win-win for everyone.

**Comment by srush** [comment]
It's incredibly contributor friendly! Come help out. It's only a week old

**Comment by ghost** [comment]
I meant, like it lacks documentation on what needs to be done more etc.

**Comment by srush** [comment]
I added a Work Plan: https://github.com/harvardnlp/namedtensor/projects/1 , let me know if you have other ideas.
