### ISSUE TITLE
Update Examples for ".spec()"

### ISSUE THREAD

**Issue by Ricocotam** [harvardnlp/namedtensor#95]
Hi,
Would it be possible to have an example of how `.spec()` works and how to use it on custom modules ?

Once made, I'd be happy to PR new examples and add this to existing ones

**Comment by srush** [comment]
Hi Adrien, 

This is definitely a work in progress, but the current custom api would look something like this: 

https://github.com/harvardnlp/namedtensor/blob/master/examples/transformer/modules.py#L7

Happy for feedback though!

**Comment by Ricocotam** [comment]
I looked at it but I didn't understand how we define what's
